### ISSUE TITLE
Split Authentification and Authorization

### ISSUE THREAD

**Issue by stephanebastian** [eclipse-vertx/vertx-auth#309]
This issue is an umbrella to talk about providing a better separation between Authentication and Authorization in Vertx

A RFC has been written to capture the main goals: 
https://github.com/assembloo/vertx-auth/wiki/RFC_Auth_Improvements

Some discussions have already started on the google group:
https://groups.google.com/forum/#!topic/vertx-dev/TQTlzGq9HlY

And also on Gitter.

Here is a list of task that need to be done:
- [x] Add the interface Authorization along with related interfaces and impls  (No breaking changes)
- [x] Add the method User.authorizations() (No breaking changes)
- [x] Update each Auth implementation #313 
- [x] Investigate whether or not it's possible to replace all custom User implementations (JWTUser, JDBCUSer, etc.) with one UserImpl #314
- [x] Update  web handlers to support the new Authorization mechanism #315

Note that this issue is related to #272

**Comment by pmlopes** [comment]
All issues have been addressed

**Comment by lukehutch** [comment]
Thanks for the work on this. Have the new APIs been documented yet?

**Comment by pmlopes** [comment]
The basic concepts are in the asciidoc:

https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-common/src/main/asciidoc/index.adoc

Examples from the adoc can be found on:

https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-common/src/main/java/examples/AuthCommonExamples.java

And the same for each module. On vertx-web the same has been done, API upgrade + new docs

**Comment by stephanebastian** [comment]
I'll be able to help on this over the week-end

just let me know at then of the day if you still need help on this

**Comment by pmlopes** [comment]
@stephanebastian just go over the asciidocs and see if it needs more information. I might have been to light on the details ;-)

**Comment by lukehutch** [comment]
Nit: The API uses the US spelling "Authorization", but the docs use the British English spelling "Authorisation". Probably should change the doc spelling to match the API spelling.

**Comment by pmlopes** [comment]
:+1: the original API was using the British spelling but I've moved it to American due to the fact that the terms authn/authz are more popular and only apply to us spelling. 

@lukehutch are you willing to do a pull request?

**Comment by lukehutch** [comment]
Submitted a PR.

**Comment by stephanebastian** [comment]
Hi all,
I read this part this morning  https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-common/src/main/asciidoc/index.adoc and it looks good :+1:  

I am wondering though if we should talk about the AuthorizationContext whose role is to glue together the User and other data relevant to perform the authorization (ie: ipaddress) ? 
I am going to write a blurb about it and send a PR.

@lukehutch anything else that might relevant to add ?

**Comment by lukehutch** [comment]
@stephanebastian Unfortunately I'm really "out of the think of it" right now, I was up to my neck in all the auth{z|n} stuff back when I filed #272, but had to move on to other projects, and I'm swamped right now so probably won't have time to look closely at the new API or the documentation for a while. However if you do want to make sure the API is right before 4.0 is launched, it might be worth it to double check something wasn't missed by wading through all the points I made in #272 (which are complex -- sorry). That issue may help as a sanity check.

**Comment by stephanebastian** [comment]
@lukehutch Luke, I looked at #272 one more time and I believe that all issues can be addressed by the Authn / AuthZ improvements that are coming-up in 4.0

**Comment by lukehutch** [comment]
@stephanebastian that's awesome, thanks for verifying! I appreciate everyone's work on this.

**Comment by stephanebastian** [comment]
@pmlopes I've made a PR with some minor comments on vertx-auth. I'll llok at vertx-web at the end of the day
@lukehutch I guess the 'moment of truth' will be when you use the new stuff and see if it works for you or is easier than it was before :smiley:  Hopefully I think we are in good shape.
Thanks,
all the best
